// Visible copy and accessible labels in both languages.
window.siteContent = {
  "en": {
    "skip": "Skip to content",
    "nav.label": "Main navigation",
    "nav.directions": "Focus",
    "nav.about": "Background",
    "nav.contact": "Contact",
    "preferences": "Display preferences",
    "hero.identity": "WANG TIANHONG / NOLAN",
    "hero.line1": "Intelligence",
    "hero.line2": "for the",
    "hero.line3": "real world.",
    "hero.intro": "I'm Nolan, an AI PhD student at Westlake University. I work on robot learning and enjoy building useful tools with AI.",
    "hero.explore": "Explore projects",
    "portrait.alt": "Portrait of Wang Tianhong",
    "portrait.caption": "PhD student · Westlake University",
    "hero.location": "BASED IN HANGZHOU, CHINA",
    "motion.pause": "Pause motion",
    "hero.scroll": "Scroll to directions",
    "directions.eyebrow": "01 / FOCUS",
    "directions.title": "Areas of focus",
    "directions.intro": "My work moves between robots, language models, and everyday software. I like following an idea far enough to see what it can do.",
    "directions.robotics": "Robotics",
    "directions.roboticsText": "Exploring how robots perceive, learn, and act, with a focus on embodied AI and world models.",
    "directions.roboticsNote": "Perception → Action",
    "directions.ai": "Artificial intelligence",
    "directions.aiText": "Building language models and AI tools, and exploring more natural ways to work with them.",
    "directions.aiNote": "Models → Tools",
    "directions.systems": "Enterprise systems",
    "directions.systemsText": "Building software that connects knowledge, business workflows, and the people who use it.",
    "directions.systemsNote": "Software → Workflows",
    "work.robotics": "Robotics",
    "work.dinoflow": "DINOv3 · Flow matching · Robot learning",
    "work.openvla": "Reproduction · VLA · Fine-tuning",
    "work.models": "AI models",
    "work.minillm": "From scratch · Transformer · PyTorch",
    "work.tools": "AI tools",
    "work.wiki": "Knowledge base · Retrieval · Obsidian",
    "work.xiaolingTitle": "Xiaoling",
    "work.xiaoling": "Voice · Vision · Memory",
    "work.systems": "Systems",
    "work.tbcrm": "Enterprise software · Business workflows",
    "about.eyebrow": "02 / BACKGROUND",
    "about.title": "Education & experience",
    "about.intro": "I came to AI through mechanical engineering and mechatronics. That background shapes how I approach research: with curiosity, experiments, and a habit of building things.",
    "about.now": "NOW",
    "about.westlake": "Westlake University",
    "about.phd": "PhD student · Artificial Intelligence",
    "about.msc": "MSc",
    "about.kit": "Karlsruhe Institute of Technology",
    "about.master": "Mechatronics and Information Technology",
    "about.bachelorLabel": "BACHELOR",
    "about.cumt": "China University of Mining and Technology",
    "about.bachelor": "Mechanical Engineering",
    "contact.eyebrow": "03 / CONTACT",
    "contact.title": "Let's compare notes.",
    "contact.personal": "Personal",
    "contact.academic": "Academic",
    "footer.top": "Back to top ↑",
    "page.back": "Back to home",
    "page.switch": "Other areas",
    "page.projects": "Projects",
    "page.roboticsCount": "2 projects",
    "page.aiCount": "3 projects",
    "page.systemsCount": "1 project",
    "page.contact": "Let's compare notes ↗",
    "page.view": "View projects →",
    "meta.description": "Wang Tianhong (Nolan), AI PhD student at Westlake University. Research and engineering in robotics, artificial intelligence, and enterprise software.",
    "page.roboticsDescription": "Robot learning, embodied AI, and world models. Selected robotics projects by Wang Tianhong (Nolan).",
    "page.aiDescription": "Language models, AI tools, and human–AI interaction. Selected artificial intelligence projects by Wang Tianhong (Nolan).",
    "page.systemsDescription": "Enterprise software, knowledge systems, and business workflows. Selected software projects by Wang Tianhong (Nolan).",
    "art.robotics": "A sculptural robotic arm",
    "art.ai": "A flowing sculpture of interwoven filaments",
    "art.systems": "A modular architectural sculpture",
    "about.education": "Education",
    "about.experience": "Experience & collaboration",
    "about.season": "Season 2024",
    "about.westlakeLogo": "Westlake University logo",
    "about.kitLogo": "Karlsruhe Institute of Technology logo",
    "about.cumtLogo": "China University of Mining and Technology logo",
    "brand.home": "Nolan home",
    "brand.pageName": "Nolan",
    "portrait.name": "Wang Tianhong",
    "footer.copyright": "© 2026 Wang Tianhong",
    "meta.title": "Nolan · Wang Tianhong — Robotics, AI & Systems",
    "contact.intro": "I'm happy to talk research, explore a project idea, or just swap notes on something interesting.",
    "experience.karaceing": "KA-RaceIng",
    "experience.auo": "AUO",
    "experience.kia": "Dongfeng Yueda Kia",
    "experience.keyence": "KEYENCE",
    "experience.xcmg": "XCMG Group"
  },
  "zh": {
    "skip": "跳到正文",
    "nav.label": "主要导航",
    "nav.directions": "方向",
    "nav.about": "背景",
    "nav.contact": "联系",
    "preferences": "显示偏好",
    "hero.identity": "王天虹 / NOLAN",
    "hero.line1": "让智能",
    "hero.line2": "走进",
    "hero.line3": "真实世界。",
    "hero.intro": "我是王天虹（Nolan），在西湖大学读人工智能方向博士，研究机器人学习，也喜欢动手做 AI 工具。",
    "hero.explore": "查看项目",
    "portrait.alt": "王天虹的个人照片",
    "portrait.caption": "博士生 · 西湖大学",
    "hero.location": "中国 · 杭州",
    "motion.pause": "暂停动画",
    "hero.scroll": "向下浏览研究方向",
    "directions.eyebrow": "01 / 方向",
    "directions.title": "探索方向",
    "directions.intro": "关注机器人、语言模型和日常使用的软件。喜欢顺着一个想法往下探索，看看它能做些什么。",
    "directions.robotics": "机器人",
    "directions.roboticsText": "探索机器人如何感知、学习与行动，关注具身智能和世界模型。",
    "directions.roboticsNote": "感知 → 行动",
    "directions.ai": "人工智能",
    "directions.aiText": "理解语言模型，也动手做 AI 工具，探索更自然的人机交互。",
    "directions.aiNote": "模型 → 工具",
    "directions.systems": "企业系统",
    "directions.systemsText": "围绕知识管理与业务流程，做更顺手、更清晰的企业软件。",
    "directions.systemsNote": "软件 → 业务流程",
    "work.robotics": "机器人",
    "work.models": "AI 模型",
    "work.tools": "AI 工具",
    "work.systems": "企业系统",
    "work.dinoflow": "DINOv3 · 流匹配 · 机器人学习",
    "work.openvla": "复现 · VLA · 微调",
    "work.minillm": "从零实现 · Transformer · PyTorch",
    "work.wiki": "知识库 · 信息检索 · Obsidian",
    "work.xiaolingTitle": "小灵",
    "work.xiaoling": "语音 · 视觉 · 记忆",
    "work.tbcrm": "企业软件 · 业务流程",
    "about.eyebrow": "02 / 背景",
    "about.title": "教育与经历",
    "about.intro": "我的学习经历从机械工程，经过机电与信息技术，走到了人工智能。喜欢理解原理，也习惯用代码和实验把想法试一遍。",
    "about.now": "目前",
    "about.westlake": "西湖大学",
    "about.phd": "博士生 · 人工智能",
    "about.msc": "硕士",
    "about.kit": "卡尔斯鲁厄理工学院",
    "about.master": "机电与信息技术",
    "about.bachelorLabel": "本科",
    "about.cumt": "中国矿业大学",
    "about.bachelor": "机械工程",
    "contact.eyebrow": "03 / 联系",
    "contact.title": "聊聊新想法",
    "contact.personal": "个人邮箱",
    "contact.academic": "学术邮箱",
    "footer.top": "回到顶部 ↑",
    "page.back": "返回首页",
    "page.switch": "其他方向",
    "page.projects": "项目",
    "page.roboticsCount": "2 个项目",
    "page.aiCount": "3 个项目",
    "page.systemsCount": "1 个项目",
    "page.contact": "聊聊新想法 ↗",
    "page.view": "查看项目 →",
    "meta.description": "王天虹（Nolan），西湖大学人工智能方向博士生，关注机器人、人工智能与企业软件的研究和工程实践。",
    "page.roboticsDescription": "机器人学习、具身智能与世界模型。王天虹（Nolan）的机器人方向精选项目。",
    "page.aiDescription": "语言模型、AI 工具与人机交互。王天虹（Nolan）的人工智能方向精选项目。",
    "page.systemsDescription": "企业软件、知识系统与业务流程。王天虹（Nolan）的企业软件精选项目。",
    "art.robotics": "机器人方向主题视觉：精密机械臂",
    "art.ai": "人工智能方向主题视觉：交织的流动线束",
    "art.systems": "企业系统方向主题视觉：互联的模块建筑",
    "about.education": "教育背景",
    "about.experience": "合作与经历",
    "about.season": "2024 赛季",
    "about.westlakeLogo": "西湖大学标识",
    "about.kitLogo": "卡尔斯鲁厄理工学院标识",
    "about.cumtLogo": "中国矿业大学标识",
    "brand.home": "王天虹（Nolan）首页",
    "brand.pageName": "王天虹",
    "portrait.name": "王天虹",
    "footer.copyright": "© 2026 王天虹",
    "meta.title": "王天虹 · Nolan — 机器人、AI 与企业系统",
    "contact.intro": "有感兴趣的研究问题、想一起做的项目，或者只是想分享一个想法，都欢迎来信。",
    "experience.karaceing": "KA-RaceIng",
    "experience.auo": "友达光电",
    "experience.kia": "东风悦达起亚",
    "experience.keyence": "基恩士",
    "experience.xcmg": "徐工集团"
  }
};
