// Visible copy and accessible labels in both languages.
window.siteContent = {
  "en": {
    "skip": "Skip to content",
    "nav.label": "Main navigation",
    "nav.directions": "Directions",
    "nav.work": "Work",
    "nav.about": "About",
    "nav.contact": "Contact",
    "preferences": "Display preferences",
    "hero.identity": "TIANHONG WANG / NOLAN",
    "hero.line1": "Intelligence",
    "hero.line2": "for the",
    "hero.line3": "real world.",
    "hero.intro": "I'm Nolan, an AI PhD student at Westlake University, exploring robot learning, language models, and enterprise software.",
    "hero.explore": "Explore my work",
    "portrait.alt": "Portrait of Tianhong Wang",
    "portrait.caption": "PhD student · Westlake University",
    "hero.location": "BASED IN HANGZHOU, CHINA",
    "motion.pause": "Pause motion",
    "hero.scroll": "Scroll to directions",
    "directions.eyebrow": "01 / RESEARCH & ENGINEERING",
    "directions.title1": "Research meets",
    "directions.title2": "engineering.",
    "directions.intro": "Three connected areas: intelligent machines, AI tools, and software for real work.",
    "directions.robotics": "Robotics",
    "directions.roboticsText": "Robot learning, embodied AI, and world models.",
    "directions.roboticsNote": "Perception → Action",
    "directions.ai": "Artificial intelligence",
    "directions.aiText": "Language models, AI tools, and human–AI interaction.",
    "directions.aiNote": "Models → Tools",
    "directions.systems": "Enterprise systems",
    "directions.systemsText": "Enterprise software, knowledge systems, and business workflows.",
    "directions.systemsNote": "Software → Workflows",
    "work.eyebrow": "02 / SELECTED WORK",
    "work.title": "Selected projects.",
    "work.more": "More on GitHub",
    "work.robotics": "Robotics",
    "work.dinoflow": "DINOv3 · Flow matching · Robot learning",
    "work.openvla": "Reproduction · VLA · Fine-tuning",
    "work.models": "AI models",
    "work.minillm": "From scratch · Transformer · PyTorch",
    "work.tools": "AI tools",
    "work.wiki": "Knowledge base · Retrieval · Obsidian",
    "work.xiaolingTitle": "Xiaoling",
    "work.xiaoling": "Voice · Vision · Memory",
    "work.systems": "Systems",
    "work.tbcrm": "Enterprise software · Business workflows",
    "about.eyebrow": "03 / BACKGROUND",
    "about.title1": "Grounded in engineering.",
    "about.title2": "Driven by research.",
    "about.intro": "My background spans mechanical engineering, mechatronics, and artificial intelligence. I connect research with hands-on work in robotics and software.",
    "about.now": "NOW",
    "about.westlake": "Westlake University",
    "about.phd": "PhD student · Artificial Intelligence",
    "about.msc": "MSc",
    "about.kit": "Karlsruhe Institute of Technology",
    "about.master": "Mechatronics and Information Technology",
    "about.bachelorLabel": "BACHELOR",
    "about.cumt": "China University of Mining and Technology",
    "about.bachelor": "Mechanical Engineering",
    "about.racing": "Autonomous Systems · Velocity Estimation",
    "contact.eyebrow": "04 / GET IN TOUCH",
    "contact.title1": "For research",
    "contact.title2": "and collaboration.",
    "contact.personal": "Personal",
    "contact.academic": "Academic",
    "footer.top": "Back to top ↑",
    "page.back": "Back to home",
    "page.switch": "Explore another direction",
    "page.projects": "Selected projects",
    "page.roboticsCount": "02 projects",
    "page.aiCount": "03 projects",
    "page.systemsCount": "01 project",
    "page.contact": "Get in touch ↗",
    "page.view": "View projects →",
    "meta.description": "Tianhong Wang (Nolan), AI PhD student at Westlake University. Research and engineering in robotics, artificial intelligence, and enterprise software.",
    "page.roboticsDescription": "Robot learning, embodied AI, and world models. Selected robotics projects by Tianhong Wang (Nolan).",
    "page.aiDescription": "Language models, AI tools, and human–AI interaction. Selected artificial intelligence projects by Tianhong Wang (Nolan).",
    "page.systemsDescription": "Enterprise software, knowledge systems, and business workflows. Selected software projects by Tianhong Wang (Nolan).",
    "art.robotics": "A sculptural robotic arm",
    "art.ai": "A flowing sculpture of interwoven filaments",
    "art.systems": "A modular architectural sculpture"
  },
  "zh": {
    "skip": "跳到正文",
    "nav.label": "主要导航",
    "nav.directions": "方向",
    "nav.work": "项目",
    "nav.about": "关于",
    "nav.contact": "联系",
    "preferences": "显示偏好",
    "hero.identity": "TIANHONG WANG / NOLAN",
    "hero.line1": "从研究出发，",
    "hero.line2": "让智能走进",
    "hero.line3": "真实世界。",
    "hero.intro": "我是 Nolan，西湖大学人工智能方向博士生，关注机器人学习、语言模型与企业软件。",
    "hero.explore": "探索我的工作",
    "portrait.alt": "Tianhong Wang 的个人照片",
    "portrait.caption": "博士生 · 西湖大学",
    "hero.location": "中国 · 杭州",
    "motion.pause": "暂停动画",
    "hero.scroll": "向下浏览研究方向",
    "directions.eyebrow": "01 / 研究与工程",
    "directions.title1": "以研究探索，",
    "directions.title2": "以工程实现。",
    "directions.intro": "三个相互连接的方向：智能机器、AI 工具与业务系统。",
    "directions.robotics": "机器人",
    "directions.roboticsText": "机器人学习、具身智能与世界模型。",
    "directions.roboticsNote": "感知 → 行动",
    "directions.ai": "人工智能",
    "directions.aiText": "语言模型、AI 工具与人机交互。",
    "directions.aiNote": "模型 → 工具",
    "directions.systems": "企业系统",
    "directions.systemsText": "企业应用、知识系统与业务流程。",
    "directions.systemsNote": "软件 → 业务流程",
    "work.eyebrow": "02 / 精选项目",
    "work.title": "研究与工程实践。",
    "work.more": "在 GitHub 查看更多",
    "work.robotics": "机器人",
    "work.models": "AI 模型",
    "work.tools": "AI 工具",
    "work.systems": "企业系统",
    "work.dinoflow": "DINOv3 · 流匹配 · 机器人学习",
    "work.openvla": "复现 · 视觉语言动作模型 · 微调",
    "work.minillm": "从零实现 · Transformer · PyTorch",
    "work.wiki": "知识库 · 信息检索 · Obsidian",
    "work.xiaolingTitle": "小灵",
    "work.xiaoling": "语音 · 视觉 · 记忆",
    "work.tbcrm": "企业软件 · 业务流程",
    "about.eyebrow": "03 / 关于我",
    "about.title1": "以工程为基础，",
    "about.title2": "以研究为方向。",
    "about.intro": "我的学术背景涵盖机械工程、机电与信息技术，以及人工智能，关注研究与机器人、软件实践的结合。",
    "about.now": "目前",
    "about.westlake": "西湖大学",
    "about.phd": "博士生 · 人工智能",
    "about.msc": "硕士",
    "about.kit": "卡尔斯鲁厄理工学院",
    "about.master": "机电与信息技术",
    "about.bachelorLabel": "本科",
    "about.cumt": "中国矿业大学",
    "about.bachelor": "机械工程",
    "about.racing": "无人驾驶系统 · 速度估计",
    "contact.eyebrow": "04 / 联系我",
    "contact.title1": "欢迎交流，",
    "contact.title2": "探讨研究与合作。",
    "contact.personal": "个人邮箱",
    "contact.academic": "学术邮箱",
    "footer.top": "回到顶部 ↑",
    "page.back": "返回首页",
    "page.switch": "探索其他方向",
    "page.projects": "精选项目",
    "page.roboticsCount": "02 个项目",
    "page.aiCount": "03 个项目",
    "page.systemsCount": "01 个项目",
    "page.contact": "联系我 ↗",
    "page.view": "查看项目 →",
    "meta.description": "Tianhong Wang（Nolan），西湖大学人工智能方向博士生，关注机器人、人工智能与企业软件的研究和工程实践。",
    "page.roboticsDescription": "机器人学习、具身智能与世界模型。Tianhong Wang（Nolan）的机器人方向精选项目。",
    "page.aiDescription": "语言模型、AI 工具与人机交互。Tianhong Wang（Nolan）的人工智能方向精选项目。",
    "page.systemsDescription": "企业软件、知识系统与业务流程。Tianhong Wang（Nolan）的企业软件精选项目。",
    "art.robotics": "机器人方向主题视觉：精密机械臂",
    "art.ai": "人工智能方向主题视觉：交织的流动线束",
    "art.systems": "企业系统方向主题视觉：互联的模块建筑"
  }
};
