// Visible copy and accessible labels in both languages.
window.siteContent = {
  "en": {
    "skip": "Skip to content",
    "nav.label": "Main navigation",
    "nav.directions": "Directions",
    "nav.work": "Work",
    "nav.about": "About",
    "nav.contact": "Contact",
    "preferences": "Display preferences",
    "hero.identity": "TIANHONG WANG / NOLAN",
    "hero.line1": "From ideas",
    "hero.line2": "to real-world",
    "hero.line3": "intelligence.",
    "hero.intro": "I'm Nolan, an AI PhD student at Westlake University. I explore how intelligence learns, moves, and becomes useful in everyday systems.",
    "hero.explore": "Explore my directions",
    "portrait.alt": "Portrait of Tianhong Wang",
    "portrait.caption": "PhD student · Westlake University",
    "hero.location": "BASED IN HANGZHOU, CHINA",
    "motion.pause": "Pause motion",
    "hero.scroll": "Scroll to directions",
    "directions.eyebrow": "01 / WHAT I EXPLORE",
    "directions.title1": "One curiosity.",
    "directions.title2": "Three directions.",
    "directions.intro": "From understanding the physical world to building tools that people can use.",
    "directions.robotics": "Robotics",
    "directions.roboticsText": "Robot learning, embodied AI, and world models.",
    "directions.roboticsNote": "Perception → Action",
    "directions.ai": "Artificial intelligence",
    "directions.aiText": "Language models, useful tools, and natural interactions.",
    "directions.aiNote": "Models → Tools",
    "directions.systems": "Enterprise systems",
    "directions.systemsText": "Enterprise applications, knowledge systems, and business workflows.",
    "directions.systemsNote": "Ideas → Everyday use",
    "work.eyebrow": "02 / SELECTED WORK",
    "work.title": "A few things I've built.",
    "work.more": "More on GitHub",
    "work.robotics": "Robotics",
    "work.dinoflow": "Visual learning · Robot actions",
    "work.openvla": "Reproduction · Vision-language-action",
    "work.models": "AI models",
    "work.minillm": "From scratch · Language models",
    "work.tools": "AI tools",
    "work.wiki": "Knowledge base · Local AI",
    "work.xiaolingTitle": "Xiaoling",
    "work.xiaoling": "Voice · Vision · Memory",
    "work.systems": "Systems",
    "work.tbcrm": "Enterprise applications · Business systems",
    "about.eyebrow": "03 / A LITTLE CONTEXT",
    "about.title1": "An engineer's curiosity.",
    "about.title2": "A researcher's mindset.",
    "about.intro": "My path runs from mechanical engineering to mechatronics and now artificial intelligence. I like understanding how things work—and making ideas work in practice.",
    "about.now": "NOW",
    "about.westlake": "Westlake University",
    "about.phd": "PhD student · Artificial Intelligence",
    "about.msc": "MSc",
    "about.kit": "Karlsruhe Institute of Technology",
    "about.master": "Mechatronics and Information Technology",
    "about.bachelorLabel": "BACHELOR",
    "about.cumt": "China University of Mining and Technology",
    "about.bachelor": "Mechanical Engineering",
    "about.racing": "Autonomous System · Velocity Estimation",
    "contact.eyebrow": "04 / GET IN TOUCH",
    "contact.title1": "Good ideas start",
    "contact.title2": "with a conversation.",
    "contact.personal": "Personal",
    "contact.academic": "Academic",
    "footer.top": "Back to top ↑",
    "page.back": "Back to home",
    "page.switch": "Explore another direction",
    "page.projects": "Related projects",
    "page.roboticsCount": "02 projects",
    "page.aiCount": "03 projects",
    "page.systemsCount": "01 project",
    "page.contact": "Get in touch ↗"
  },
  "zh": {
    "skip": "跳到正文",
    "nav.label": "主要导航",
    "nav.directions": "方向",
    "nav.work": "项目",
    "nav.about": "关于",
    "nav.contact": "联系",
    "preferences": "显示偏好",
    "hero.identity": "TIANHONG WANG / NOLAN",
    "hero.line1": "从想法出发，",
    "hero.line2": "让智能走进",
    "hero.line3": "真实世界。",
    "hero.intro": "我是 Nolan，西湖大学人工智能方向博士生。我关注智能如何学习、行动，以及如何应用于日常工具和业务系统。",
    "hero.explore": "了解我的方向",
    "portrait.alt": "Tianhong Wang 的个人照片",
    "portrait.caption": "博士生 · 西湖大学",
    "hero.location": "中国 · 杭州",
    "motion.pause": "暂停动画",
    "hero.scroll": "向下浏览研究方向",
    "directions.eyebrow": "01 / 我的方向",
    "directions.title1": "一份好奇心，",
    "directions.title2": "三个探索方向。",
    "directions.intro": "从理解物理世界，到构建真正可用的工具与系统。",
    "directions.robotics": "机器人",
    "directions.roboticsText": "机器人学习、具身智能与世界模型。",
    "directions.roboticsNote": "感知 → 行动",
    "directions.ai": "人工智能",
    "directions.aiText": "语言模型、实用工具与自然交互。",
    "directions.aiNote": "模型 → 工具",
    "directions.systems": "企业系统",
    "directions.systemsText": "企业应用、知识系统与业务流程。",
    "directions.systemsNote": "想法 → 实际应用",
    "work.eyebrow": "02 / 精选项目",
    "work.title": "一些动手实践。",
    "work.more": "在 GitHub 查看更多",
    "work.robotics": "机器人",
    "work.models": "AI 模型",
    "work.tools": "AI 工具",
    "work.systems": "企业系统",
    "work.dinoflow": "视觉学习 · 机器人动作",
    "work.openvla": "复现 · 视觉语言动作模型",
    "work.minillm": "从零实现 · 语言模型",
    "work.wiki": "知识库 · 本地 AI",
    "work.xiaolingTitle": "小灵",
    "work.xiaoling": "语音 · 视觉 · 记忆",
    "work.tbcrm": "企业应用 · 业务系统",
    "about.eyebrow": "03 / 关于我",
    "about.title1": "工程师的好奇心，",
    "about.title2": "研究者的思考方式。",
    "about.intro": "从机械工程、机电与信息技术，到如今的人工智能，我一直喜欢理解事物的运行方式，也喜欢将想法落到实处。",
    "about.now": "目前",
    "about.westlake": "西湖大学",
    "about.phd": "博士生 · 人工智能",
    "about.msc": "硕士",
    "about.kit": "卡尔斯鲁厄理工学院",
    "about.master": "机电与信息技术",
    "about.bachelorLabel": "本科",
    "about.cumt": "中国矿业大学",
    "about.bachelor": "机械工程",
    "about.racing": "无人驾驶系统 · 速度估计",
    "contact.eyebrow": "04 / 联系我",
    "contact.title1": "好的想法，",
    "contact.title2": "从一次交流开始。",
    "contact.personal": "个人邮箱",
    "contact.academic": "学术邮箱",
    "footer.top": "回到顶部 ↑",
    "page.back": "返回首页",
    "page.switch": "探索其他方向",
    "page.projects": "相关项目",
    "page.roboticsCount": "02 个项目",
    "page.aiCount": "03 个项目",
    "page.systemsCount": "01 个项目",
    "page.contact": "联系我 ↗"
  }
};
